# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c894876891091e6be6e6f08778b485fa"
application_url = "https://provinces-puppy-junction-frank.trycloudflare.com"
embedded = true
name = "Smart Order Tag Email Alerts D"
handle = "smart-order-tag-email-alerts-d"

[build]
include_config_on_deploy = true
dev_store_url = "generated-store-1.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://provinces-puppy-junction-frank.trycloudflare.com/auth/callback",
  "https://provinces-puppy-junction-frank.trycloudflare.com/auth/shopify/callback",
  "https://provinces-puppy-junction-frank.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
